Weather UI using RecyclerView and CardView
brenpardal/WeatherApp pull request #4
Opened 2021-01-29 18:18 UTC by brenpardal

### **WHAT'S NEW**
**This update includes:**
* Development of the WeatherApp UI
* Show the weather information for the next five days into a cardView in a RecyclerView

#### *Preview Nexus S:*
![nexus_s)](https://user-images.githubusercontent.com/73835964/106312084-e5f0e500-6244-11eb-9922-13d43d8be62f.png)

#### *Preview Pixel 2XL:*
![pixel_2xl)](https://user-images.githubusercontent.com/73835964/106312333-3a946000-6245-11eb-93c1-c21456b1a962.png)

2021-01-29 18:29 UTC, SartiMau requested changes

2021-01-29 18:29 UTC, SartiMau commented on app/src/main/java/com/weatherapp/adapter/WeatherAdapter.kt
> +        private const val CELSIUS = "°C"
put this string in the resources pls

2021-01-29 18:29 UTC, SartiMau commented on app/src/main/java/com/weatherapp/adapter/WeatherAdapter.kt
> +        private const val REAL_FEEL = "RealFeel "
same

2021-01-29 19:07 UTC, brenpardal commented on app/src/main/java/com/weatherapp/adapter/WeatherAdapter.kt
> +        private const val CELSIUS = "°C"
Solved!

2021-01-29 19:15 UTC, brenpardal commented on app/src/main/java/com/weatherapp/adapter/WeatherAdapter.kt
> +        private const val REAL_FEEL = "RealFeel "
Solved!

2021-01-29 19:40 UTC, nicolbidone commented on app/src/main/java/com/weatherapp/data/service/WeatherService.kt
> +    fun getWeather(id: String): Observable<List<Data>> {
please give Data class a more informative name like WeatherData

2021-01-29 19:40 UTC, nicolbidone commented on app/src/main/java/com/weatherapp/data/service/WeatherService.kt
> +                response.body()?.list?.filter { it.date.contains(HOUR) }?.let { subscriber.onNext(mapper.transformData(it)) }
please give transformData a more informative name like transformWeatherData

2021-01-29 19:40 UTC, nicolbidone commented on app/src/main/java/com/weatherapp/data/mapper/WeatherMapper.kt
>      }
here you can use " = this.map { it.mapToWeatherData() } " and use an extension function to map the data

2021-01-29 19:40 UTC, nicolbidone commented on app/src/main/java/com/weatherapp/data/mapper/WeatherMapper.kt
>  class WeatherMapper {
why do you wrap the mappers in a class?

2021-01-29 19:53 UTC, brenpardal commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
Thanks. Solved!

2021-01-29 19:55 UTC, brenpardal commented on app/src/main/java/com/weatherapp/data/service/WeatherService.kt
> +    fun getWeather(id: String): Observable<List<Data>> {
Solved.

2021-01-29 19:59 UTC, brenpardal commented on app/src/main/java/com/weatherapp/data/service/WeatherService.kt
> +                response.body()?.list?.filter { it.date.contains(HOUR) }?.let { subscriber.onNext(mapper.transformData(it)) }
Solved.

2021-02-01 14:25 UTC, brenpardal commented on app/src/main/java/com/weatherapp/data/mapper/WeatherMapper.kt
>      }
Solved. I used an extension function to map the data.

2021-02-01 14:26 UTC, brenpardal commented on app/src/main/java/com/weatherapp/data/mapper/WeatherMapper.kt
>  class WeatherMapper {
Solved.  I use an extension function to map the data now.

2021-02-01 16:18 UTC, mauroLonghi commented on app/src/main/res/layout/weather_item.xml
> +    app:layout_constraintTop_toTopOf="parent">
1)Why you are using constraints guides if dont have a constriant as a parent?
2) why use a wrap size iff you need to show in all the screen?

2021-02-01 16:49 UTC, SartiMau approved these changes

2021-02-01 17:11 UTC, lucianoeli approved these changes

2021-02-01 17:33 UTC, brenpardal commented on app/src/main/res/layout/weather_item.xml
> +    app:layout_constraintTop_toTopOf="parent">
Solved.
1) Removed this. 
2) Replaced by match_parent.

2021-02-01 17:43 UTC, mauroLonghi approved these changes

2021-02-01 17:47 UTC, BQuinteros approved these changes

2021-02-01 18:55 UTC, nicolbidone approved these changes

2021-02-01 18:55 UTC, merged