Dialog Fragment
brenpardal/WeatherApp pull request #5
Opened 2021-02-03 16:17 UTC by brenpardal

### **WHAT'S NEW**
**This update includes:**
* If the user taps on one of the items in the forecast list, the details of the forecast with extended information for that day are displayed in a DialogFragment.

#### *Preview on Nexus S device:*
![nexus_s](https://user-images.githubusercontent.com/73835964/106774823-4a36ee80-6621-11eb-83a5-9ec752afd3c3.gif)

#### *Preview on Pixel 2XL device:*
![pixel_2xl](https://user-images.githubusercontent.com/73835964/106774856-5327c000-6621-11eb-96aa-94d968c52135.gif)

2021-02-03 16:28 UTC, mauroLonghi commented on README.md
> +##### 02/02/2021
today its Wednesday 3 of February :p

2021-02-03 16:30 UTC, mauroLonghi commented on app/src/main/java/com/weatherapp/adapter/WeatherAdapter.kt
> +    private val weatherComplete: List<WeatherData>
why you have 2 list of wheather?

2021-02-03 16:36 UTC, brenpardal commented on README.md
> +##### 02/02/2021
Changed. I uploaded it yesterday hahaha

2021-02-03 16:58 UTC, brenpardal commented on app/src/main/java/com/weatherapp/adapter/WeatherAdapter.kt
> +    private val weatherComplete: List<WeatherData>
Because one is the filtered weather list and the other is the complete list returned from the service. I replaced weather by weatherFiltered.

2021-02-03 17:13 UTC, SartiMau requested changes

2021-02-03 17:13 UTC, SartiMau commented on app/src/main/java/com/weatherapp/adapter/WeatherAdapter.kt
> +    private val weatherComplete: List<WeatherData>
You should have only one list here and call the adapter with the processed data when it's needed

2021-02-03 17:13 UTC, SartiMau commented on app/src/main/java/com/weatherapp/adapter/WeatherAdapter.kt
> +                when {
instead of this you can use an if else statement

2021-02-04 13:43 UTC, brenpardal commented on app/src/main/java/com/weatherapp/adapter/WeatherAdapter.kt
> +                when {
Solved!

2021-02-04 13:45 UTC, brenpardal commented on app/src/main/java/com/weatherapp/adapter/WeatherAdapter.kt
> +    private val weatherComplete: List<WeatherData>
Solved!

2021-02-04 14:03 UTC, mauroLonghi commented on app/src/main/java/com/weatherapp/mvp/contract/WeatherDetailContract.kt
> +        fun retrieveWeather(date: String, weatherList: ArrayList<WeatherData>)
not use ArrayList pls, it's kotlin...use a List or a mutableList

2021-02-04 14:07 UTC, SartiMau requested changes

2021-02-04 14:07 UTC, SartiMau commented on app/src/main/java/com/weatherapp/activity/MainActivity.kt
> +        presenter.goToFragment(date)
please put a more representative name here

2021-02-04 14:07 UTC, SartiMau commented on app/src/main/java/com/weatherapp/mvp/presenter/WeatherDetailPresenter.kt
> +        val forecastFiltered = forecast.filter { it.date.contains(formatDay.format(formatJson.parse(date))) }
this filter should be in the model

2021-02-04 14:07 UTC, SartiMau commented on app/src/main/java/com/weatherapp/mvp/view/WeatherDetailView.kt
> +        binding.recyclerViewWeather.adapter = WeatherAdapter(weatherFiltered, null)
instead of passing a null here, you can put a default value in the WeatherAdapter's constructor

2021-02-04 14:18 UTC, brenpardal commented on app/src/main/java/com/weatherapp/mvp/contract/WeatherDetailContract.kt
> +        fun retrieveWeather(date: String, weatherList: ArrayList<WeatherData>)
Solved.

2021-02-04 14:20 UTC, brenpardal commented on app/src/main/java/com/weatherapp/mvp/presenter/WeatherDetailPresenter.kt
> +        val forecastFiltered = forecast.filter { it.date.contains(formatDay.format(formatJson.parse(date))) }
Solved.

2021-02-04 14:39 UTC, brenpardal commented on app/src/main/java/com/weatherapp/mvp/view/WeatherDetailView.kt
> +        binding.recyclerViewWeather.adapter = WeatherAdapter(weatherFiltered, null)
Thanks Mau, solved.

2021-02-04 14:51 UTC, brenpardal commented on app/src/main/java/com/weatherapp/activity/MainActivity.kt
> +        presenter.goToFragment(date)
Solved!

2021-02-04 14:54 UTC, BQuinteros approved these changes

2021-02-04 16:51 UTC, mauroLonghi approved these changes

2021-02-04 16:51 UTC, merged